version: 2
project_name: nnav

before:
  hooks:
    - go mod tidy

builds:
  - id: nnav
    main: ./cmd/nnav
    binary: nnav
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

archives:
  - id: tarballs
    builds: [nnav]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums_{{ .Version }}.txt"

nfpms:
  - id: packages
    # Emit both .deb and .rpm
    formats: [deb, rpm]
    package_name: nnav
    builds: [nnav]
    bindir: /usr/bin
    vendor: Brian McJilton
    maintainer: Brian McJilton <brian.mcjilton@gmail.com>
    description: "nnav — terminal notes navigator (TUI) for .md/.txt; opens in your editor"
    license: MIT
    homepage: https://github.com/brianmcjilton/nnav
    contents:
      - src: LICENSE
        dst: /usr/share/doc/nnav/LICENSE
      - src: README.md
        dst: /usr/share/doc/nnav/README.md
    umask: 0o022

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # With `--snapshot`, nothing is published. Remove/adjust when you start tagging real releases.
  footer: |-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

